url: "https://stgolem.me"
baseurl: ""
lang: "ru-RU"

title: Привет парни!
description: Что бы вот это вот так, надо вот это вот сюда, а вот то вот туда. И главное тут не это вот!

theme: jekyll-theme-hacker
